inherit:
    - models/modulo10.yaml
    - wandb.yaml

model:
    n_dims: 16
    n_positions: 4096
    linear_embedding: True

training:
    task: modulo10
    test_len : 50
    batch_size: 64
    learning_rate: 0.0001
    train_steps: 100001
    curriculum:
        points:
            start: 2
            end: 26
            inc: 1
            interval: 500

out_dir: ../models/modulo10
# out_dir: /nobackup/yingfan/new_models/without/modulo10
test_run: False
wandb:
    name: "modulo10"
