inherit: 
    - models/multi.yaml
    - wandb.yaml

model:
    n_dims: 6
    n_positions: 4096
    linear_embedding: True

training:
    task: multi
    test_len : 15
    batch_size: 64
    learning_rate: 0.0001
    train_steps: 100001
    curriculum:
        points:
            start: 2
            end: 12
            inc: 1
            interval: 500

out_dir: ../models/multi
test_run: False
wandb:
    name: "multi"