inherit: 
    - models/parity.yaml
    - wandb.yaml

model:
    n_dims: 6
    n_positions: 4096
    linear_embedding: True

training:
    task: parity
    test_len : 40
    batch_size: 64
    learning_rate: 0.0001
    train_steps: 100001
    curriculum:
        points:
            start: 2
            end: 21
            inc: 1
            interval: 500

out_dir: ../models/parity
# out_dir: /nobackup/yingfan/new_models/without/parity
test_run: False
wandb:
    name: "parity"